# Generated by Django 3.1.3 on 2020-11-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfDay', models.DateField()),
                ('Weekday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Period', models.IntegerField()),
                ('Content', models.TextField()),
                ('Note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Schoolclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=80)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grading', models.IntegerField()),
                ('LessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.lesson')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.students')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalendarWeek', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='kalender.day')),
                ('Monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Monday', to='kalender.day')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.teacher')),
                ('Thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Thursday', to='kalender.day')),
                ('Tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tuesday', to='kalender.day')),
                ('Wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wednesday', to='kalender.day')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='ClassID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.schoolclass'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='DayID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.day'),
        ),
    ]
