# Generated by Django 3.1.3 on 2020-11-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfDay', models.DateField()),
                ('Weekday', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSpan', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Schoolclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=80)),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grading', models.IntegerField()),
                ('DayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.day')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.students')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CalendarWeek', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='kalender.day')),
                ('Monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='kalender.day')),
                ('TeacherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.teacher')),
                ('Thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='kalender.day')),
                ('Tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='kalender.day')),
                ('Wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='kalender.day')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Content', models.TextField()),
                ('Note', models.TextField()),
                ('ClassID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.schoolclass')),
                ('DayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.day')),
                ('PeriodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalender.period')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentgrading',
            constraint=models.UniqueConstraint(fields=('StudentID', 'TeacherID', 'DayID'), name='StudentGradingUnique'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('TeacherID', 'CalendarWeek', 'Year'), name='UniqueSchedule'),
        ),
    ]
